project_id = "smewvpzgpykfmpvwijps"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch-rss-articles.import_map]]
name = "supabase"
url = "https://deno.land/x/supabase@1.112.0/mod.ts"

[[fetch-rss-articles.import_map]]
name = "std"
url = "https://deno.land/std@0.168.0/mod.ts"