// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://smewvpzgpykfmpvwijps.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZXd2cHpncHlrZm1wdndpanBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxODczMzAsImV4cCI6MjA0ODc2MzMzMH0.Mr8uYQIpCWO3tQUaWEJWHaY8lG441y4fVzb9u76vsdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);